
services:
  postgres:
    restart: always
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - transcendence
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  backend_user:
    depends_on:
      - postgres
    container_name: users
    build:
      context: .
      dockerfile: docker/backend_user/Dockerfile
    volumes:
      - ./users:/app
    ports:
      - "8001:8001"
    env_file:
      - .env
    networks:
      - transcendence
    restart: always

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: nginx
    ports:
      - "3042:3042"
    volumes:
      - ./docker/nginx/frontend:/usr/share/nginx/frontend
    networks:
      - transcendence
    restart: always
    depends_on:
      - backend_user

networks:
  transcendence:
    name: transcendence
    driver: bridge

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: "/home/rcortes-b/ft_transcendence42/data/postgres"
      o: bind
